### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [ashishb/android-security-awesome#11]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by dweinstein** [comment]
Not everything listed in this repo is open source but I guess the repo itself might be :-)

**Comment by jeffreyjackson** [comment]
its a good starting point, can you come on board and help?  You'll be an admin.

**Comment by dweinstein** [comment]
I'm not the owner of this repo, just thought I'd mention it though ;-)

**Comment by jeffreyjackson** [comment]
thanks @dweinstein :smile:

**Comment by bugwrangler** [comment]
Sure will contribute :+1:
