### ISSUE TITLE
`JD-GUI` link broken

### ISSUE THREAD

**Issue by arthurvr** [ashishb/android-security-awesome#12]
This link seems to be returning a 404 for me:

> JD-GUI - Java decompiler

**Comment by ashishb** [comment]
Thanks Arthur, I updated the link to point to https://github.com/java-decompiler/jd-gui
in https://github.com/ashishb/android-security-awesome/commit/f181b1b32215a0fc6fbd522c46760d77cb193345#diff-04c6e90faac2675aa89e2176d2eec7d8
