### ISSUE TITLE
Add a `contributing.md` file

### ISSUE THREAD

**Issue by arthurvr** [ashishb/android-security-awesome#14]
With clear guidelines when and how to contribute.

See https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines

**Comment by ashishb** [comment]
Fixed in https://github.com/ashishb/android-security-awesome/commit/2037ac070b902c9d79808ff3e0daa2cf7afb6f66

**Comment by arthurvr** [comment]
Yay! Thanks :)
