### ISSUE TITLE
Adding Pithus for online analyzers

### ISSUE THREAD

**Issue by christalib** [ashishb/android-security-awesome#141]
Hi! This is a really nice list. Would you consider adding [Pithus](https://beta.pithus.org/) to the list of online analyzer? It's built on top of some of tools that already mentioned and allows also users to hunt for malwares with Yara rules in its most recent update 🚀

**Comment by ashishb** [comment]
Sure, please send a PR.

**Comment by christalib** [comment]
Thanks! Opened: https://github.com/ashishb/android-security-awesome/pull/142
