### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by harshitSingh1** [ashishb/android-security-awesome#184]
how to use this repo for apk vuln scanning

**Comment by IBViraCo** [comment]
1) Download and extract the GitHub project (Download ZIP file)
2) Open a Terminal in the extracted directory
3) Enter the codes below:
`sudo apt install cargo`
`cargo install urlsup`
`./run_awesome_bot.sh`

**Comment by ashishb** [comment]
> how to use this repo for apk vuln scanning

This repo only lists the tools.
You have to run the tools manually.
