### ISSUE TITLE
Locked phone 

### ISSUE THREAD

**Issue by MarkMoffitt74** [ashishb/android-security-awesome#202]
Is there a code run threw browser T-Mobile can't unlock it an Walmart doesn't care so any ideals still great phone.

**Comment by joshuakings231** [comment]
Hello

**Comment by MarkMoffitt74** [comment]
Yes hey hope all do wonderful you and your's it's this darn phone is in really great shape it's just for a phone sure was a gift T-Mobile said phone wasn't there stock it who I bought it off of and called Walmart and was told if they could get it unloaded I'd be getting 40-50 bux phone for couple bux but well I'd have say anyone goin fall in

**Comment by joshuakings231** [comment]
Yo bro, I do not understand what you mean, what you talking about?

**Comment by MarkMoffitt74** [comment]
Josh I thank ya and got app to open up phone is what it said but I thank you for come back if there's anything I could help you out with just tell an I'll definitely be there have great weekend when you get to it
