### ISSUE TITLE
the best one

### ISSUE THREAD

**Issue by dinasaif** [ashishb/android-security-awesome#39]
Hi ,
Thanks for your effort, but I have some questions:
1- How can I make static analysis to get all permissions and APIS from APK file without decomile it?
2- Which tool can I use with *## windows 7 * 
3- I want to know the goal from dynamic analysis (I know that it uses to determine the application behavior )
4-  Which tool can I use with *## windows 7 * in dynamic analysis that output report to me for every Apk
Thanks for your help

**Comment by ashishb** [comment]
In my humble opinion, decompiling is the easiest route for 1.
Not sure about 2 and 4. I didn't what you want with 3.

**Comment by dinasaif** [comment]
thanks for your reply
