### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by ReadmeCritic** [ashishb/android-security-awesome#54]
- [L034] 404 http://www.foresafe.com/scan  
- [L121] 404 https://github.com/BaiduSecurityLabs/ZjDroid  
- [L121] 404 https://github.com/yangbean9/ZjDroid  

please consider removing?

**Comment by ReadmeCritic** [comment]
More dead links
-  http://www.androidsandbox.net/

**Comment by ashishb** [comment]
Removed
