### ISSUE TITLE
Resources from up and coming book

### ISSUE THREAD

**Issue by binarymist** [ashishb/android-security-awesome#58]
Would you be interested in resources once my [third fascicle](https://leanpub.com/holistic-infosec-for-web-developers-fascicle2-mobile-iot) of [Holistic Info-Sec for Web Developers](https://leanpub.com/b/holisticinfosecforwebdevelopers) is under-way? If so, I'll add my self a reminder to pass my resources on to you in the form of PRs

**Comment by ashishb** [comment]
Sure Kim. Pull requests are always welcome.
